import time
from common_imports import *

kill_app_instance('Dialpad')
open_application('/Applications/Dialpad.app')
verify_application_open('Dialpad')
time.sleep(7)
get_cpu_usage_for_app('Dialpad')
get_memory_usage_for_app('Dialpad')
get_disk_space_for_app('Dialpad')
wait_for_seconds(seconds=4)
# text = "No unread conversations"
# find_text_on_screen(text=text)
# hover_on_text(text=text)
# click_on_text(text=text)
# double_click_on_text(text=text)
locate_and_click("/Users/swapnil/PycharmProjects/CodeLess Automation/code/ui-locators/cta-call-button.png")
click_on_text("type a name or number")
write_on_ui("9599066811")
wait_for_seconds(seconds=1)
press_single_key("enter")
wait_for_seconds(seconds=5)
locate_and_click("/Users/swapnil/PycharmProjects/CodeLess Automation/code/ui-locators/new-message.png")
wait_for_seconds(seconds=1)
write_on_ui("Hello")
press_single_key("enter")
